### PR TITLE
Remove Map Selection button and logic

### PR DESCRIPTION
**Pull request by m4rtint**

### CODE REVIEW

**Comment by m4rtint** [comment]
[End game panel need fixing](https://trello.com/c/PrbPXM8e/740-end-game-panel-need-fixing)

**Comment by m4rtint** [comment]
[End game panel need fixing](https://trello.com/c/PrbPXM8e/740-end-game-panel-need-fixing)

**Comment by mikeslgoh** [comment]
Should I wait for Jocelyn's reply or can I approve this?

**Comment by m4rtint** [comment]
> Should I wait for Jocelyn's reply or can I approve this?

Approve it.

**Pull request merged**
