### PR TITLE
Feature/winter land bug fixes

### PR DESCRIPTION
**Pull request by wbeltran777**
- Added invisible walls to winterland
- Fixed invisible wall glitch next to igloo
- Modified terrain
- Changed Material to work with URP (That's why the buildings were invisible in the build)

### CODE REVIEW

**Review by mikeslgoh — APPROVED** [review]

**Comment by m4rtint** [comment]
@wbeltran777 What was wrong with the Cabbage material? i'm guessing not URP compliant? 

And can you rename it properly? 8BC34A isn't a good name

**Comment by m4rtint** [comment]
- I checked the cabbage prefab, it's missing the material

**Comment by m4rtint** [comment]
There'se a SnowBackground terrain as a child of SnowTerrain, 
Is there a usecase for this?

**Comment by wbeltran777** [comment]
> There'se a SnowBackground terrain as a child of SnowTerrain,
> Is there a usecase for this?

Yeah it's been there for a while. Culling through snow left a visible void, so that background is in the back to make up for that. Now that we don't have snow walls to cull through though, I'll go ahead and remove it

**Review by m4rtint — APPROVED** [review]

**Comment by mikeslgoh** [comment]
[Cant drop from highground in winterland mountain (near igloo)](https://trello.com/c/4qLTwSCs/743-cant-drop-from-highground-in-winterland-mountain-near-igloo)

**Comment by mikeslgoh** [comment]
[Culling around winterland needed](https://trello.com/c/4eMmgEbf/860-culling-around-winterland-needed)

**Pull request merged**
