### PR TITLE
Feature/clean up winter land

### PR DESCRIPTION
**Pull request by wbeltran777**
Winterland Clean up

Not final version unfortunately, but way closer to the final product
Might be worth merging the work now to test out how the design is feeling, and make changes in the next few weeks

- Replaced old roads with new road tool kit
- Added present obstacles
- Experimenting with verticality!
- Snowman has colliders for each section
new winterLand

### CODE REVIEW

**Comment by m4rtint** [comment]
Can you Reorganize the hierachy?
Screen Shot 2020-08-24 at 11 15 27 PM

**Comment by m4rtint** [comment]
@wbeltran777 Ahh it looks much cleaner now. 
But you missed this part. not sure what it is. 
Screen Shot 2020-08-25 at 12 31 28 AM

**Comment by wbeltran777** [comment]
> @wbeltran777 Ahh it looks much cleaner now.
> But you missed this part. not sure what it is.
> Screen Shot 2020-08-25 at 12 31 28 AM

OOps! Updating now. Lots of prefabs lost their refs cause I was moving stuff around, it's mostly fine, but this must be a leftover from that

**Comment by mikeslgoh** [comment]
[Clean up Winterland (3.0)](https://trello.com/c/78iAH9xm/769-clean-up-winterland-30)

**Pull request merged**
