### PR TITLE
New Skins and hat

### PR DESCRIPTION
**Pull request by m4rtint**
image

- Added in New Santa Hat
- Added in new ornate skins

### CODE REVIEW

**Comment by m4rtint** [comment]
[Import Magan's models - cars/hat skins (0.5)](https://trello.com/c/3TlP9VYB/772-import-magans-models-cars-hat-skins-05)

**Comment by m4rtint** [comment]
[Add revised Car skins and Santa Hat](https://trello.com/c/WYUCU80M/789-add-revised-car-skins-and-santa-hat)

**Comment by Gursaanj** [comment]
So there is no Hat Icon for the Santa's hat yet??

**Comment by m4rtint** [comment]
> So there is no Hat Icon for the Santa's hat yet??

no

**Comment by mikeslgoh** [comment]
> > So there is no Hat Icon for the Santa's hat yet??
> 
> no

there is the straw hat and santa hat icon here: https://drive.google.com/drive/folders/1oOL7LiFoNL9pd8SmxCG4jvz9wfmjVy-x

**Comment by m4rtint** [comment]
> > > So there is no Hat Icon for the Santa's hat yet??
> > 
> > 
> > no
> 
> there is the straw hat and santa hat icon here: https://drive.google.com/drive/folders/1oOL7LiFoNL9pd8SmxCG4jvz9wfmjVy-x
> She's currently working on the chef hat icon right now but not sure if you want to import that on its own later

i'll just add it in. Might as well

**Pull request merged**
