### PR TITLE
Remove cache instruction from builds

### PR DESCRIPTION
**Pull request by mikeslgoh**
The builds failed due to caching so I'm removing it - tested and the builds are fine

### CODE REVIEW

**Comment by m4rtint** [comment]
Why is caching causing problems?

**Comment by mikeslgoh** [comment]
> Why is caching causing problems?

For some reason the build failed previously plus for our builds, we don't seem to use caching anyway.
image

**Comment by m4rtint** [comment]
> > Why is caching causing problems?
> 
> For some reason the build failed previously plus for our builds, we don't seem to use caching anyway.
> image

Were you able to find out why it might be timing out?

**Comment by mikeslgoh** [comment]
> > > Why is caching causing problems?
> > 
> > 
> > For some reason the build failed previously plus for our builds, we don't seem to use caching anyway.
> > image
> 
> Were you able to find out why it might be timing out?

@m4rtint no ... there isn't anything I could find that would be the cause

**Comment by mikeslgoh** [comment]
Closing this PR because it looks like I just needed to re-run the build job

**Pull request closed without merging**
