### PR TITLE
Feature/crown hat

### PR DESCRIPTION
**Pull request by m4rtint**
image

### CODE REVIEW

**Comment by m4rtint** [comment]
[Add more hats into the game](https://trello.com/c/CBS7b4Ao/506-add-more-hats-into-the-game)

**Comment by wbeltran777** [comment]
How come there's a change on ParkingSpot.meta?

**Comment by m4rtint** [comment]
@wbeltran777 i think i moved it around

**Comment by mikeslgoh** [comment]
Test cases failed because of meta files for some reason

**Pull request merged**
