### PR TITLE
Installing the Debug Console from the store

### PR DESCRIPTION
**Pull request by m4rtint**
It's not placed into the scene yet. 
this is just the download

Just approve or comment if you want this in or not

### CODE REVIEW

**Comment by m4rtint** [comment]
@mikeslgoh yes. so we get to see any errors popped up on builds. 
I haven't integrated it yet, just downloaded

**Comment by m4rtint** [comment]
@Gursaanj too much in terms of space or what?

**Comment by m4rtint** [comment]
@Gursaanj you should try out this branch first. and then see if it's too much

**Comment by mikeslgoh** [comment]
> Having the errors being shown in the builds would be cool, but im still unsure if its too much or not!! Will probably have to test it out fully before comitting to it?!?

I think it could be helpful since whenever we do builds we never know what's happening. How easy is the setup after downloading the plugin?

**Comment by m4rtint** [comment]
> > Having the errors being shown in the builds would be cool, but im still unsure if its too much or not!! Will probably have to test it out fully before comitting to it?!?
> 
> I think it could be helpful since whenever we do builds we never know what's happening. How easy is the setup after downloading the plugin?

It's just a prefab u drag and drop

**Pull request merged**
