### PR TITLE
Bugfix/winter land clean up

### PR DESCRIPTION
**Pull request by wbeltran777**
- Cleaned up random floor bumps in terrain
- Added one more power up
- Scooched large snow man so it doesnt clip through the camera
- Added obstacle tag and layer for invisible walls. Now powerups shouldn't go through the edge of the map

### CODE REVIEW

**Comment by m4rtint** [comment]
Screen Shot 2020-09-28 at 11 11 14 PM


Does this need a tag?

**Comment by m4rtint** [comment]
Screen Shot 2020-09-28 at 11 13 51 PM
Check the buildings and the present need the obstcle tag?

**Comment by mikeslgoh** [comment]
[Add more details to maps - Winterland (0.5)](https://trello.com/c/WrKvVy4d/846-add-more-details-to-maps-winterland-05)

**Comment by wbeltran777** [comment]
Yes to both of those comments, will update with those objects tagged

**Review by m4rtint — APPROVED** [review]

**Review by mikeslgoh — APPROVED** [review]

**Pull request merged**
